spring:
  data:
    mongodb:
      uri: 'mongodb+srv://zabogdan:vDwSIlWIyLCVML46@zawebsite.k2dgi.mongodb.net/JavaCompiler?retryWrites=true&w=majority'

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: 'http://127.0.0.1:8761/eureka'
server:
  servlet:
    context-path: /auth
  port: 8882