server:
  port: 3000
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: 'http://127.0.0.1:8761/eureka'
jwt:
  secret: 'helloWorld'
  lifeSpan: 86400000
spring:
  application:
    name: gateway
