server:
  port: 3000
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: 'http://127.0.0.1:8761/eureka'
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
          - id: auth-service
            uri: lb://auth-service
            predicates:
            - Path=/auth/**
management:
  endpoints:
    web:
      exposure:
        include: '*'