spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native
  security:
    user:
      password: 'helloWorld'

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: 'http://127.0.0.1:8881/eureka'

server:
  port: 8880
