spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared/dev
  profiles:
    active: native
  security:
    user:
      password: 'helloWorld'

server:
  port: 8880
